# Complete Project 4: Winner Stays: European Football Analysis with Streaks and Countries

# Scenario
You are a junior data analyst working for a business intelligence consultant. You have been at your job for six months, and your boss feels you are ready for more responsibility. He has asked you to lead a project for a brand new client — this will involve everything from defining the business task all the way through presenting your data-driven recommendations. You will choose the topic, ask the right questions, identify a fresh dataset and ensure its integrity, conduct analysis, create compelling data visualizations, and prepare a presentation.

# Main question to answer:
1. What type of company does your client represent, and what are they asking you to accomplish?
2. What are the key factors involved in the business task you are investigating?
3. What type of data will be appropriate for your analysis?
4. Where will you obtain that data?
5. Who is your audience, and what materials will help you present to them effectively?

# 1.0 Ask
After elaborating the first analysis, I would like to improve it, adding new metrics based on functions and adding new visualizations such as maps for practice.

Let's remember the rules: We start in the year 2022, the current champion is Real Madrid after winning the 2001-2002 Champions League Title. From then on and, in every league or cup match, the crown is played. Every time someone manages to defeat him, he conquers the crown and takes it until he is beaten or it reigns a new champion (annually in the final of the Cahmpions League).

# 2.0 Prepare
## 2.1 Loading libraries
```
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(geomtextpath)
library(lubridate)
library(forcats)
library(viridis)
```

## 2.2 Data loading
```
matches <- read.csv('../input/european-soccer-data/Full_Kaggle_Dataset.csv')
```
